const mongoose = require("mongoose");
const Department = require("../src/models/Department");
require("dotenv").config();

const departmentsData = [
  // ========== SECTOR 1: Executive Leadership (IDs 1-6) ==========
  {
    id: 1,
    sectorId: 1,
    building: "A",
    floor: 7,
    room: "701",
    name: { en: "Minister's Office", am: "", om: "" },
    description: {
      en: "Executive leadership overseeing all ministry operations and strategic direction.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 7. Minister's office is straight ahead from elevator.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Executive decision making",
        "Policy approval",
        "Strategic guidance",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265700",
    email: "minister@mint.gov.et",
    walkingTime: "5 minutes",
    icon: "🏛️",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400",
    head: "Dr. Belete Molla",
    headImage: "",
    rating: 4.9,
    reviewCount: 156,
    corridorSide: "left",
    corridorOrder: 1,
    landmark: "Straight ahead from elevator",
  },
  {
    id: 2,
    sectorId: 1,
    building: "A",
    floor: 6,
    room: "601",
    name: { en: "Deputy Minister Office", am: "", om: "" },
    description: {
      en: "Deputy minister's office supporting ministerial operations.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 6. Deputy office is first door on right.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Policy coordination",
        "Strategic planning",
        "Inter-ministerial relations",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265701",
    email: "deputy@mint.gov.et",
    walkingTime: "4 minutes",
    icon: "👔",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400",
    head: "Dr. Bayisa Bedada",
    headImage: "",
    rating: 4.8,
    reviewCount: 89,
    corridorSide: "right",
    corridorOrder: 1,
    landmark: "Near elevator",
  },
  {
    id: 3,
    sectorId: 1,
    building: "A",
    floor: 4,
    room: "401",
    name: { en: "Leadership Chief Executive", am: "", om: "" },
    description: {
      en: "Chief executive overseeing daily ministry operations.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 4. Room 401 at the end of corridor.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Operational management",
        "Executive coordination",
        "Strategic execution",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265702",
    email: "ceo@mint.gov.et",
    walkingTime: "4 minutes",
    icon: "👤",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "Ato Solomon Aynimar",
    headImage: "",
    rating: 4.7,
    reviewCount: 67,
    corridorSide: "",
    corridorOrder: 0,
    landmark: "End of corridor",
  },
  {
    id: 4,
    sectorId: 1,
    building: "A",
    floor: 3,
    room: "310",
    name: { en: "Strategic Affairs Executive", am: "", om: "" },
    description: {
      en: "Strategic planning and coordination of ministry initiatives.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 3, turn right. Room 310 is third door.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Strategic planning",
        "Policy coordination",
        "Performance monitoring",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265703",
    email: "strategic@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "📊",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    head: "Ato Azmach Desalegn",
    headImage: "",
    rating: 4.6,
    reviewCount: 45,
    corridorSide: "right",
    corridorOrder: 3,
    landmark: "Near meeting room",
  },
  {
    id: 5,
    sectorId: 1,
    building: "A",
    floor: 3,
    room: "311",
    name: { en: "Basic Service Executive", am: "", om: "" },
    description: { en: "Basic service delivery coordination.", am: "", om: "" },
    directions: {
      en: "Take elevator to Floor 3. Room 311 is across from Strategic Affairs.",
      am: "",
      om: "",
    },
    services: {
      en: ["Service delivery", "Citizen support", "Complaint handling"],
      am: [],
      om: [],
    },
    contact: "+251-111-265704",
    email: "basicservice@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "🛠️",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "Ato Yedenekachew",
    headImage: "",
    rating: 4.5,
    reviewCount: 52,
    corridorSide: "left",
    corridorOrder: 4,
    landmark: "Across from Strategic Affairs",
  },
  {
    id: 6,
    sectorId: 1,
    building: "A",
    floor: 2,
    room: "203",
    name: { en: "Minister's Secretariat", am: "", om: "" },
    description: {
      en: "Minister's office administration and coordination.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 2. Room 203 at the end of corridor.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Meeting coordination",
        "Document management",
        "Schedule management",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265705",
    email: "secretariat@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "📁",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.6,
    reviewCount: 38,
    corridorSide: "right",
    corridorOrder: 2,
    landmark: "End of corridor",
  },

  // ========== SECTOR 2: Innovation & Technology (IDs 7-12) ==========
  {
    id: 7,
    sectorId: 2,
    building: "A",
    floor: 1,
    room: "101-102",
    name: { en: "Technology Center", am: "", om: "" },
    description: {
      en: "Technology innovation, incubation, and research center.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 1, turn right. Room 101-102 is first door. Green door with 'Technology Center' sign.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Technology incubation",
        "Innovation consulting",
        "Startup mentorship",
        "Tech research",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265710",
    email: "techcenter@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "💡",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    head: "Dr. Alemitu Bekele",
    headImage: "",
    rating: 4.8,
    reviewCount: 234,
    corridorSide: "right",
    corridorOrder: 1,
    landmark: "First door on right",
  },
  {
    id: 8,
    sectorId: 2,
    building: "A",
    floor: 2,
    room: "202",
    name: { en: "Innovation Fund Office", am: "", om: "" },
    description: {
      en: "Funding and grants for innovation projects.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 2, turn left. Room 202 is second door.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Grant applications",
        "Innovation funding",
        "Startup investment",
        "Project evaluation",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265711",
    email: "innovationfund@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "💰",
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.6,
    reviewCount: 98,
    corridorSide: "left",
    corridorOrder: 2,
    landmark: "Second door on left",
  },
  {
    id: 9,
    sectorId: 2,
    building: "A",
    floor: 5,
    room: "501",
    name: { en: "Technology Development & Transfer", am: "", om: "" },
    description: {
      en: "Technology development and transfer to industry.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 5, turn right. Room 501 at the end.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Tech transfer",
        "Industry partnership",
        "Technology commercialization",
        "R&D coordination",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265712",
    email: "techdev@mint.gov.et",
    walkingTime: "4 minutes",
    icon: "⚙️",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400",
    head: "Dr. Worku Mekonnen",
    headImage: "",
    rating: 4.7,
    reviewCount: 112,
    corridorSide: "right",
    corridorOrder: 3,
    landmark: "End of corridor",
  },
  {
    id: 10,
    sectorId: 2,
    building: "A",
    floor: 6,
    room: "602",
    name: { en: "Startup", am: "", om: "" },
    description: {
      en: "Startup support, incubation, and acceleration programs.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 6. Room 602 is near the elevator.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Startup incubation",
        "Mentorship",
        "Networking events",
        "Pitch training",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265713",
    email: "startup@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "🚀",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.9,
    reviewCount: 67,
    corridorSide: "",
    corridorOrder: 0,
    landmark: "Near elevator",
  },
  {
    id: 11,
    sectorId: 2,
    building: "A",
    floor: 5,
    room: "502",
    name: { en: "Innovation & Technology Cooperation", am: "", om: "" },
    description: {
      en: "International cooperation and partnership coordination.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 5. Room 502 next to Technology Development.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "International partnership",
        "Knowledge exchange",
        "Collaboration programs",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265714",
    email: "cooperation@mint.gov.et",
    walkingTime: "4 minutes",
    icon: "🤝",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.5,
    reviewCount: 56,
    corridorSide: "right",
    corridorOrder: 2,
    landmark: "Next to Tech Development",
  },
  {
    id: 12,
    sectorId: 2,
    building: "A",
    floor: 5,
    room: "503",
    name: { en: "Research & Development", am: "", om: "" },
    description: {
      en: "National research and development coordination.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 5, turn left. Room 503 at the end.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Research coordination",
        "Grant management",
        "Research evaluation",
        "Publication support",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265715",
    email: "randd@mint.gov.et",
    walkingTime: "4 minutes",
    icon: "🔬",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.6,
    reviewCount: 78,
    corridorSide: "left",
    corridorOrder: 3,
    landmark: "End of left corridor",
  },

  // ========== SECTOR 3: Finance & Administration (IDs 13-15) ==========
  {
    id: 13,
    sectorId: 3,
    building: "A",
    floor: 3,
    room: "301",
    name: { en: "Treasury & Finance Office", am: "", om: "" },
    description: {
      en: "Budget management and financial operations.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 3, turn left. Room 301 is first door.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Budget planning",
        "Financial reporting",
        "Payment processing",
        "Expense tracking",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265720",
    email: "finance@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "💰",
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400",
    head: "W/o Etalemew Gezahegn",
    headImage: "",
    rating: 4.4,
    reviewCount: 156,
    corridorSide: "left",
    corridorOrder: 1,
    landmark: "First door on left",
  },
  {
    id: 14,
    sectorId: 3,
    building: "A",
    floor: 4,
    room: "402",
    name: { en: "Procurement & Finance Executive", am: "", om: "" },
    description: {
      en: "Government procurement and contract management.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 4, turn right. Room 402 is second door.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Tender management",
        "Vendor registration",
        "Contract awards",
        "Supplier evaluation",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265721",
    email: "procurement@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "📦",
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=400",
    head: "W/o Etalemew Gezahegn",
    headImage: "",
    rating: 4.3,
    reviewCount: 98,
    corridorSide: "right",
    corridorOrder: 2,
    landmark: "Second door on right",
  },
  {
    id: 15,
    sectorId: 3,
    building: "A",
    floor: 2,
    room: "201",
    name: { en: "Audit Office Executive", am: "", om: "" },
    description: {
      en: "Internal audit and compliance monitoring.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 2. Room 201 is first door on left.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Internal audit",
        "Compliance review",
        "Risk assessment",
        "Financial audit",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265722",
    email: "audit@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "🔍",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.5,
    reviewCount: 67,
    corridorSide: "left",
    corridorOrder: 1,
    landmark: "First door on left",
  },

  // ========== SECTOR 4: Policy & Strategy (IDs 16-17) ==========
  {
    id: 16,
    sectorId: 4,
    building: "A",
    floor: 4,
    room: "404",
    name: { en: "Policy & Strategic Affairs", am: "", om: "" },
    description: {
      en: "Policy development and strategic planning.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 4, turn left. Room 404 at the end.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Policy research",
        "Strategy formulation",
        "Policy analysis",
        "Impact assessment",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265730",
    email: "policy@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "📋",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.6,
    reviewCount: 89,
    corridorSide: "left",
    corridorOrder: 4,
    landmark: "End of left corridor",
  },
  {
    id: 17,
    sectorId: 4,
    building: "A",
    floor: 5,
    room: "503",
    name: { en: "National Research & Development", am: "", om: "" },
    description: {
      en: "National R&D strategy and coordination.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 5. Room 503 near the staircase.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "R&D strategy",
        "Research funding",
        "Innovation policy",
        "Technology assessment",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265731",
    email: "nationalrd@mint.gov.et",
    walkingTime: "4 minutes",
    icon: "🔬",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.5,
    reviewCount: 56,
    corridorSide: "left",
    corridorOrder: 3,
    landmark: "Near staircase",
  },

  // ========== SECTOR 5: HR & Competency (IDs 18-19) ==========
  {
    id: 18,
    sectorId: 5,
    building: "A",
    floor: 3,
    room: "302",
    name: { en: "Competency & HR Management", am: "", om: "" },
    description: {
      en: "Human resource management and competency development.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 3, turn right. Room 302 near the meeting room.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Recruitment",
        "Training programs",
        "Performance evaluation",
        "Employee relations",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265740",
    email: "hr@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "👥",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400",
    head: "Ato Dagne Assefa",
    headImage: "",
    rating: 4.5,
    reviewCount: 123,
    corridorSide: "right",
    corridorOrder: 2,
    landmark: "Near meeting room",
  },
  {
    id: 19,
    sectorId: 5,
    building: "A",
    floor: 4,
    room: "403",
    name: { en: "Women & Social Resources", am: "", om: "" },
    description: {
      en: "Women's empowerment and social resource management.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 4. Room 403 next to Procurement.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Women's programs",
        "Social support",
        "Gender equality",
        "Capacity building",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265741",
    email: "women@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "👩",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.4,
    reviewCount: 67,
    corridorSide: "left",
    corridorOrder: 2,
    landmark: "Next to Procurement",
  },

  // ========== SECTOR 6: Operations & Services (IDs 20-22) ==========
  {
    id: 20,
    sectorId: 6,
    building: "A",
    floor: 3,
    room: "303",
    name: { en: "General Services Executive", am: "", om: "" },
    description: {
      en: "General services and facility management.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 3, turn left. Room 303 at the end.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Facility management",
        "Maintenance",
        "Cleaning services",
        "Security coordination",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265750",
    email: "services@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "🔧",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.4,
    reviewCount: 89,
    corridorSide: "left",
    corridorOrder: 5,
    landmark: "End of left corridor",
  },
  {
    id: 21,
    sectorId: 6,
    building: "A",
    floor: 3,
    room: "303",
    name: { en: "Facility Operations Executive", am: "", om: "" },
    description: {
      en: "Building operations and facility coordination.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 3. Room 303 is shared office.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Building operations",
        "Utility management",
        "Space allocation",
        "Asset management",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265751",
    email: "operations@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "⚙️",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.3,
    reviewCount: 56,
    corridorSide: "left",
    corridorOrder: 5,
    landmark: "Shared office at end",
  },
  {
    id: 22,
    sectorId: 6,
    building: "B",
    floor: 1,
    room: "110",
    name: { en: "Registry Office", am: "", om: "" },
    description: {
      en: "Document registry and records management.",
      am: "",
      om: "",
    },
    directions: {
      en: "Enter Building B. Registry Office is first door on left. Room 110.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Document registration",
        "Record keeping",
        "File management",
        "Document retrieval",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265752",
    email: "registry@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "📁",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.5,
    reviewCount: 78,
    corridorSide: "left",
    corridorOrder: 1,
    landmark: "First door on left",
  },

  // ========== SECTOR 7: Digital & ICT (IDs 23-25) ==========
  {
    id: 23,
    sectorId: 7,
    building: "A",
    floor: 1,
    room: "105",
    name: { en: "ICT Director", am: "", om: "" },
    description: {
      en: "ICT services and digital infrastructure.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 1, turn left. Room 105 is third door.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Network services",
        "IT support",
        "System development",
        "Digital infrastructure",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265760",
    email: "ict@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "🌐",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400",
    head: "Ato Denber Getahun",
    headImage: "",
    rating: 4.7,
    reviewCount: 134,
    corridorSide: "left",
    corridorOrder: 3,
    landmark: "Third door on left",
  },
  {
    id: 24,
    sectorId: 7,
    building: "B",
    floor: 1,
    room: "115",
    name: { en: "E-Electronics & E-Government", am: "", om: "" },
    description: {
      en: "E-government services and digital transformation.",
      am: "",
      om: "",
    },
    directions: {
      en: "Enter Building B, first floor. Room 115 at the end of corridor.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "E-service delivery",
        "Digital platform management",
        "Online services",
        "Digital transformation",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265761",
    email: "egov@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "💻",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.6,
    reviewCount: 98,
    corridorSide: "right",
    corridorOrder: 4,
    landmark: "End of right corridor",
  },
  {
    id: 25,
    sectorId: 7,
    building: "B",
    floor: 2,
    room: "205",
    name: { en: "ICT & Digital Economy Deputy", am: "", om: "" },
    description: {
      en: "Digital economy strategy and implementation.",
      am: "",
      om: "",
    },
    directions: {
      en: "Enter Building B, take stairs to Floor 2. Room 205 on the right.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Digital economy policy",
        "ICT strategy",
        "Innovation programs",
        "Digital inclusion",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265762",
    email: "digitaleconomy@mint.gov.et",
    walkingTime: "3 minutes",
    icon: "📈",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.5,
    reviewCount: 67,
    corridorSide: "right",
    corridorOrder: 2,
    landmark: "Second door on right",
  },

  // ========== SECTOR 8: Support Services (IDs 26-28) ==========
  {
    id: 26,
    sectorId: 8,
    building: "A",
    floor: 0,
    room: "G01",
    name: { en: "Data Center", am: "", om: "" },
    description: {
      en: "Ministry data center and server infrastructure.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Ground Floor. Data center at the end of corridor.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Server management",
        "Data storage",
        "Backup services",
        "Disaster recovery",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265770",
    email: "datacenter@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "🖥️",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.5,
    reviewCount: 45,
    corridorSide: "",
    corridorOrder: 0,
    landmark: "End of corridor",
  },
  {
    id: 27,
    sectorId: 8,
    building: "A",
    floor: 0,
    room: "G02",
    name: { en: "TV Room", am: "", om: "" },
    description: { en: "Media and broadcast facilities.", am: "", om: "" },
    directions: {
      en: "Ground Floor Building A. TV Room is near the Data Center.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Media production",
        "Broadcasting",
        "Video conferencing",
        "Recording services",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265771",
    email: "media@mint.gov.et",
    walkingTime: "2 minutes",
    icon: "📺",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.3,
    reviewCount: 34,
    corridorSide: "",
    corridorOrder: 0,
    landmark: "Near Data Center",
  },
  {
    id: 28,
    sectorId: 8,
    building: "A",
    floor: 8,
    room: "801",
    name: { en: "Conference Hall", am: "", om: "" },
    description: {
      en: "Ministry conference and meeting facilities.",
      am: "",
      om: "",
    },
    directions: {
      en: "Take elevator to Floor 8. Conference Hall is the entire floor.",
      am: "",
      om: "",
    },
    services: {
      en: [
        "Conference booking",
        "Meeting room rental",
        "Event coordination",
        "Catering services",
      ],
      am: [],
      om: [],
    },
    contact: "+251-111-265772",
    email: "conference@mint.gov.et",
    walkingTime: "1 minute",
    icon: "🏛️",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    head: "TBD",
    headImage: "",
    rating: 4.8,
    reviewCount: 89,
    corridorSide: "",
    corridorOrder: 0,
    landmark: "Entire floor",
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    await Department.deleteMany({});
    console.log("🗑️ Cleared existing departments");

    await Department.insertMany(departmentsData);
    console.log(
      `✅ Seeded ${departmentsData.length} departments with sector IDs`,
    );

    console.log("\n📊 SECTOR BREAKDOWN:");
    for (let i = 1; i <= 8; i++) {
      const count = departmentsData.filter((d) => d.sectorId === i).length;
      console.log(`   Sector ${i}: ${count} departments`);
    }

    console.log("\n🌱 Database seeding complete!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
};

seedDatabase();
